package org.lbstraw.map.domain.enumeration;

/**
 * The UsageBatiment enumeration.
 */
public enum UsageBatiment {
    LOGEMENT_COLLECTIF,
    LOGEMENT_INDIVIDUEL,
    LOGEMENT_INDIVIDUEL_GROUPE,
    BATIMENT_ADMINISTRATIF,
    BATIMENT_COMMERCIAL,
    BATIMENT_INDUSTRIEL,
    BATIMENT_DE_LOISIRS,
    BATIMENT_DE_SANTE,
    BATIMENT_DE_RETRAITE,
    BATIMENT_EDUCATIF,
    BATIMENT_SOCIO_CULTUREl,
    BATIMENT_AGRICOLE,
    OUVRAGE_EXCEPTIONNEL,
    AUTRE,
}
