export enum UsageBatiment {
  LOGEMENT_COLLECTIF = 'LOGEMENT_COLLECTIF',

  LOGEMENT_INDIVIDUEL = 'LOGEMENT_INDIVIDUEL',

  LOGEMENT_INDIVIDUEL_GROUPE = 'LOGEMENT_INDIVIDUEL_GROUPE',

  BATIMENT_ADMINISTRATIF = 'BATIMENT_ADMINISTRATIF',

  BATIMENT_COMMERCIAL = 'BATIMENT_COMMERCIAL',

  BATIMENT_INDUSTRIEL = 'BATIMENT_INDUSTRIEL',

  BATIMENT_DE_LOISIRS = 'BATIMENT_DE_LOISIRS',

  BATIMENT_DE_SANTE = 'BATIMENT_DE_SANTE',

  BATIMENT_DE_RETRAITE = 'BATIMENT_DE_RETRAITE',

  BATIMENT_EDUCATIF = 'BATIMENT_EDUCATIF',

  BATIMENT_SOCIO_CULTUREl = 'BATIMENT_SOCIO_CULTUREl',

  BATIMENT_AGRICOLE = 'BATIMENT_AGRICOLE',

  OUVRAGE_EXCEPTIONNEL = 'OUVRAGE_EXCEPTIONNEL',

  AUTRE = 'AUTRE',
}
